AWSTemplateFormatVersion: "2010-09-09"
Description: Get billing info useing serverless chrome.
Resources:
  getbillinginfofunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: '{{resolve:ssm:billing_bucket:1}}'
        S3Key: "lambda_code/get_billing_info/main.zip"
      Environment:
        Variables:
          billing_bucket: '{{resolve:ssm:billing_bucket:1}}'
          smbc_account_no: '{{resolve:ssm:smbc_account_no:2}}'
          smbc_branch_no: '{{resolve:ssm:smbc_branch_no:1}}'
          smbc_password: '{{resolve:ssm:smbc_password:1}}'
      FunctionName: "GetBillingInfo"
      Handler: "main.handler"
      Layers:
        - !Ref getbillinginfolayerchromedriver
        - !Ref getbillinginfolayerselenium
      MemorySize: 384
      Role: '{{resolve:ssm:lambda-role:1}}'
      Runtime: "python3.7"
      Tags:
        -
          Key: "Name"
          Value: "GetBillingInfo"
      Timeout: 180
      TracingConfig:
        Mode: "Active"
  getbillinginfolayerchromedriver:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - "python3.7"
      Content:
        S3Bucket: '{{resolve:ssm:billing_bucket:1}}'
        S3Key: "lambda_code/get_billing_info/layer/chromedriver.zip"
      LayerName: "GetBillingInfo_chromedriver"
  getbillinginfolayerselenium:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - "python3.7"
      Content:
        S3Bucket: '{{resolve:ssm:billing_bucket:1}}'
        S3Key: "lambda_code/get_billing_info/layer/selenium.zip"
      LayerName: "GetBillingInfo_selenium"
  getbillinginfofunctionpermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref getbillinginfofunction
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "invokegetbillinginfofunction"
          - Arn
  invokegetbillinginfofunction:
    Type: AWS::Events::Rule
    Properties:
      Name: "invokegetbillinginfofunction"
      ScheduleExpression: "cron(0 5 5 * ? *)"
      State: "ENABLED"
      Targets:
        -
          Arn:
            Fn::GetAtt:
              - "getbillinginfofunction"
              - Arn
          Id: "GetBillingInfoV1"
